name: Java CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: jdk
          distribution: 'temurin'
          architecture: x64

      - name: Create input file
        run: |
          mkdir -p src/ContaBanco/resources  # Garante que o diretório existe
          echo "2856" > src/ContaBanco/resources/input.txt
          echo "1670-8" >> src/ContaBanco/resources/input.txt
          echo "Anne Kushner" >> src/ContaBanco/resources/input.txt
          echo "237.48" >> src/ContaBanco/resources/input.txt

      - name: Check if input.txt is created
        run: |
          ls -la src/ContaBanco/resources  # Lista o diretório
          cat src/ContaBanco/resources/input.txt  # Exibe o conteúdo do arquivo
          chmod +r src/ContaBanco/resources/input.txt  # Ajusta permissões
      
      - name: Verify if ContaTerminal.java exists
        run: |
          ls -la src/ContaBanco  # Verifica se o arquivo ContaTerminal.java existe

      - name: Compile Java code
        run: |
          cd src/ContaBanco
          javac ContaTerminal.java

      - name: Run Java program
        run: |
          cd src/ContaBanco
          java ContaTerminal < resources/input.txt  # Corrigido o caminho do arquivo